/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppInstancesRouteRouteImport } from './routes/_app/instances/route'
import { Route as AppCasesRouteRouteImport } from './routes/_app/cases/route'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSessionsIndexRouteImport } from './routes/_app/sessions/index'
import { Route as AppInstancesIndexRouteImport } from './routes/_app/instances/index'
import { Route as AppHelpCenterIndexRouteImport } from './routes/_app/help-center/index'
import { Route as AppChatsIndexRouteImport } from './routes/_app/chats/index'
import { Route as AppCasesIndexRouteImport } from './routes/_app/cases/index'
import { Route as AppAppsIndexRouteImport } from './routes/_app/apps/index'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings/notifications'
import { Route as AppSettingsDisplayRouteImport } from './routes/_app/settings/display'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app/settings/appearance'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppInstancesInstanceIdRouteImport } from './routes/_app/instances/$instanceId'
import { Route as AppErrorsErrorRouteImport } from './routes/_app/errors/$error'
import { Route as AppCasesCaseIdRouteImport } from './routes/_app/cases/$caseId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppInstancesRouteRoute = AppInstancesRouteRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRouteRoute = AppCasesRouteRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRoute,
} as any)
const AppInstancesIndexRoute = AppInstancesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInstancesRouteRoute,
} as any)
const AppHelpCenterIndexRoute = AppHelpCenterIndexRouteImport.update({
  id: '/help-center/',
  path: '/help-center/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsIndexRoute = AppChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCasesRouteRoute,
} as any)
const AppAppsIndexRoute = AppAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsDisplayRoute = AppSettingsDisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppInstancesInstanceIdRoute = AppInstancesInstanceIdRouteImport.update({
  id: '/$instanceId',
  path: '/$instanceId',
  getParentRoute: () => AppInstancesRouteRoute,
} as any)
const AppErrorsErrorRoute = AppErrorsErrorRouteImport.update({
  id: '/errors/$error',
  path: '/errors/$error',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesCaseIdRoute = AppCasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => AppCasesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AppIndexRoute
  '/cases': typeof AppCasesRouteRouteWithChildren
  '/instances': typeof AppInstancesRouteRouteWithChildren
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/errors/$error': typeof AppErrorsErrorRoute
  '/instances/$instanceId': typeof AppInstancesInstanceIdRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/display': typeof AppSettingsDisplayRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/apps/': typeof AppAppsIndexRoute
  '/cases/': typeof AppCasesIndexRoute
  '/chats/': typeof AppChatsIndexRoute
  '/help-center/': typeof AppHelpCenterIndexRoute
  '/instances/': typeof AppInstancesIndexRoute
  '/sessions/': typeof AppSessionsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/users/': typeof AppUsersIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AppIndexRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/errors/$error': typeof AppErrorsErrorRoute
  '/instances/$instanceId': typeof AppInstancesInstanceIdRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/display': typeof AppSettingsDisplayRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/apps': typeof AppAppsIndexRoute
  '/cases': typeof AppCasesIndexRoute
  '/chats': typeof AppChatsIndexRoute
  '/help-center': typeof AppHelpCenterIndexRoute
  '/instances': typeof AppInstancesIndexRoute
  '/sessions': typeof AppSessionsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/users': typeof AppUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/cases': typeof AppCasesRouteRouteWithChildren
  '/_app/instances': typeof AppInstancesRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_app/': typeof AppIndexRoute
  '/_app/cases/$caseId': typeof AppCasesCaseIdRoute
  '/_app/errors/$error': typeof AppErrorsErrorRoute
  '/_app/instances/$instanceId': typeof AppInstancesInstanceIdRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/display': typeof AppSettingsDisplayRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/apps/': typeof AppAppsIndexRoute
  '/_app/cases/': typeof AppCasesIndexRoute
  '/_app/chats/': typeof AppChatsIndexRoute
  '/_app/help-center/': typeof AppHelpCenterIndexRoute
  '/_app/instances/': typeof AppInstancesIndexRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/cases'
    | '/instances'
    | '/settings'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/cases/$caseId'
    | '/errors/$error'
    | '/instances/$instanceId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps/'
    | '/cases/'
    | '/chats/'
    | '/help-center/'
    | '/instances/'
    | '/sessions/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/cases/$caseId'
    | '/errors/$error'
    | '/instances/$instanceId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/cases'
    | '/chats'
    | '/help-center'
    | '/instances'
    | '/sessions'
    | '/settings'
    | '/tasks'
    | '/users'
  id:
    | '__root__'
    | '/$'
    | '/_app'
    | '/_app/cases'
    | '/_app/instances'
    | '/_app/settings'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_app/'
    | '/_app/cases/$caseId'
    | '/_app/errors/$error'
    | '/_app/instances/$instanceId'
    | '/_app/settings/account'
    | '/_app/settings/appearance'
    | '/_app/settings/display'
    | '/_app/settings/notifications'
    | '/_app/apps/'
    | '/_app/cases/'
    | '/_app/chats/'
    | '/_app/help-center/'
    | '/_app/instances/'
    | '/_app/sessions/'
    | '/_app/settings/'
    | '/_app/tasks/'
    | '/_app/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instances': {
      id: '/_app/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof AppInstancesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instances/': {
      id: '/_app/instances/'
      path: '/'
      fullPath: '/instances/'
      preLoaderRoute: typeof AppInstancesIndexRouteImport
      parentRoute: typeof AppInstancesRouteRoute
    }
    '/_app/help-center/': {
      id: '/_app/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AppHelpCenterIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats/': {
      id: '/_app/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AppChatsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/': {
      id: '/_app/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppCasesRouteRoute
    }
    '/_app/apps/': {
      id: '/_app/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppAppsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/display': {
      id: '/_app/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AppSettingsDisplayRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/instances/$instanceId': {
      id: '/_app/instances/$instanceId'
      path: '/$instanceId'
      fullPath: '/instances/$instanceId'
      preLoaderRoute: typeof AppInstancesInstanceIdRouteImport
      parentRoute: typeof AppInstancesRouteRoute
    }
    '/_app/errors/$error': {
      id: '/_app/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AppErrorsErrorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/$caseId': {
      id: '/_app/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AppCasesCaseIdRouteImport
      parentRoute: typeof AppCasesRouteRoute
    }
  }
}

interface AppCasesRouteRouteChildren {
  AppCasesCaseIdRoute: typeof AppCasesCaseIdRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
}

const AppCasesRouteRouteChildren: AppCasesRouteRouteChildren = {
  AppCasesCaseIdRoute: AppCasesCaseIdRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
}

const AppCasesRouteRouteWithChildren = AppCasesRouteRoute._addFileChildren(
  AppCasesRouteRouteChildren,
)

interface AppInstancesRouteRouteChildren {
  AppInstancesInstanceIdRoute: typeof AppInstancesInstanceIdRoute
  AppInstancesIndexRoute: typeof AppInstancesIndexRoute
}

const AppInstancesRouteRouteChildren: AppInstancesRouteRouteChildren = {
  AppInstancesInstanceIdRoute: AppInstancesInstanceIdRoute,
  AppInstancesIndexRoute: AppInstancesIndexRoute,
}

const AppInstancesRouteRouteWithChildren =
  AppInstancesRouteRoute._addFileChildren(AppInstancesRouteRouteChildren)

interface AppSettingsRouteRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsDisplayRoute: typeof AppSettingsDisplayRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsDisplayRoute: AppSettingsDisplayRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteChildren {
  AppCasesRouteRoute: typeof AppCasesRouteRouteWithChildren
  AppInstancesRouteRoute: typeof AppInstancesRouteRouteWithChildren
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppErrorsErrorRoute: typeof AppErrorsErrorRoute
  AppAppsIndexRoute: typeof AppAppsIndexRoute
  AppChatsIndexRoute: typeof AppChatsIndexRoute
  AppHelpCenterIndexRoute: typeof AppHelpCenterIndexRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCasesRouteRoute: AppCasesRouteRouteWithChildren,
  AppInstancesRouteRoute: AppInstancesRouteRouteWithChildren,
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppErrorsErrorRoute: AppErrorsErrorRoute,
  AppAppsIndexRoute: AppAppsIndexRoute,
  AppChatsIndexRoute: AppChatsIndexRoute,
  AppHelpCenterIndexRoute: AppHelpCenterIndexRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
