/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as AppUsersRouteRouteImport } from './routes/_app/users/route'
import { Route as AppTasksRouteRouteImport } from './routes/_app/tasks/route'
import { Route as AppSessionsRouteRouteImport } from './routes/_app/sessions/route'
import { Route as AppInstancesRouteRouteImport } from './routes/_app/instances/route'
import { Route as AppCasesRouteRouteImport } from './routes/_app/cases/route'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppTgMenuIndexRouteImport } from './routes/_app/tg-menu/index'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppSessionsIndexRouteImport } from './routes/_app/sessions/index'
import { Route as AppInstancesIndexRouteImport } from './routes/_app/instances/index'
import { Route as AppCasesIndexRouteImport } from './routes/_app/cases/index'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users/$userId'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app/tasks/$taskId'
import { Route as AppSessionsSessionIdRouteImport } from './routes/_app/sessions/$sessionId'
import { Route as AppInstancesInstanceIdRouteImport } from './routes/_app/instances/$instanceId'
import { Route as AppCasesCaseIdRouteImport } from './routes/_app/cases/$caseId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRouteRoute = AppUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRouteRoute = AppTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRouteRoute = AppSessionsRouteRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppInstancesRouteRoute = AppInstancesRouteRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRouteRoute = AppCasesRouteRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppTgMenuIndexRoute = AppTgMenuIndexRouteImport.update({
  id: '/tg-menu/',
  path: '/tg-menu/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTasksRouteRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSessionsRouteRoute,
} as any)
const AppInstancesIndexRoute = AppInstancesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInstancesRouteRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCasesRouteRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppUsersRouteRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppTasksRouteRoute,
} as any)
const AppSessionsSessionIdRoute = AppSessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => AppSessionsRouteRoute,
} as any)
const AppInstancesInstanceIdRoute = AppInstancesInstanceIdRouteImport.update({
  id: '/$instanceId',
  path: '/$instanceId',
  getParentRoute: () => AppInstancesRouteRoute,
} as any)
const AppCasesCaseIdRoute = AppCasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => AppCasesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AppIndexRoute
  '/cases': typeof AppCasesRouteRouteWithChildren
  '/instances': typeof AppInstancesRouteRouteWithChildren
  '/sessions': typeof AppSessionsRouteRouteWithChildren
  '/tasks': typeof AppTasksRouteRouteWithChildren
  '/users': typeof AppUsersRouteRouteWithChildren
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/instances/$instanceId': typeof AppInstancesInstanceIdRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/cases/': typeof AppCasesIndexRoute
  '/instances/': typeof AppInstancesIndexRoute
  '/sessions/': typeof AppSessionsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/tg-menu/': typeof AppTgMenuIndexRoute
  '/users/': typeof AppUsersIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AppIndexRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/instances/$instanceId': typeof AppInstancesInstanceIdRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/cases': typeof AppCasesIndexRoute
  '/instances': typeof AppInstancesIndexRoute
  '/sessions': typeof AppSessionsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/tg-menu': typeof AppTgMenuIndexRoute
  '/users': typeof AppUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/cases': typeof AppCasesRouteRouteWithChildren
  '/_app/instances': typeof AppInstancesRouteRouteWithChildren
  '/_app/sessions': typeof AppSessionsRouteRouteWithChildren
  '/_app/tasks': typeof AppTasksRouteRouteWithChildren
  '/_app/users': typeof AppUsersRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_app/': typeof AppIndexRoute
  '/_app/cases/$caseId': typeof AppCasesCaseIdRoute
  '/_app/instances/$instanceId': typeof AppInstancesInstanceIdRoute
  '/_app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/cases/': typeof AppCasesIndexRoute
  '/_app/instances/': typeof AppInstancesIndexRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/tg-menu/': typeof AppTgMenuIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/cases'
    | '/instances'
    | '/sessions'
    | '/tasks'
    | '/users'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/cases/$caseId'
    | '/instances/$instanceId'
    | '/sessions/$sessionId'
    | '/tasks/$taskId'
    | '/users/$userId'
    | '/cases/'
    | '/instances/'
    | '/sessions/'
    | '/tasks/'
    | '/tg-menu/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/cases/$caseId'
    | '/instances/$instanceId'
    | '/sessions/$sessionId'
    | '/tasks/$taskId'
    | '/users/$userId'
    | '/cases'
    | '/instances'
    | '/sessions'
    | '/tasks'
    | '/tg-menu'
    | '/users'
  id:
    | '__root__'
    | '/$'
    | '/_app'
    | '/_app/cases'
    | '/_app/instances'
    | '/_app/sessions'
    | '/_app/tasks'
    | '/_app/users'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_app/'
    | '/_app/cases/$caseId'
    | '/_app/instances/$instanceId'
    | '/_app/sessions/$sessionId'
    | '/_app/tasks/$taskId'
    | '/_app/users/$userId'
    | '/_app/cases/'
    | '/_app/instances/'
    | '/_app/sessions/'
    | '/_app/tasks/'
    | '/_app/tg-menu/'
    | '/_app/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instances': {
      id: '/_app/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof AppInstancesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/_app/tg-menu/': {
      id: '/_app/tg-menu/'
      path: '/tg-menu'
      fullPath: '/tg-menu/'
      preLoaderRoute: typeof AppTgMenuIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppSessionsRouteRoute
    }
    '/_app/instances/': {
      id: '/_app/instances/'
      path: '/'
      fullPath: '/instances/'
      preLoaderRoute: typeof AppInstancesIndexRouteImport
      parentRoute: typeof AppInstancesRouteRoute
    }
    '/_app/cases/': {
      id: '/_app/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppCasesRouteRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppUsersRouteRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    '/_app/sessions/$sessionId': {
      id: '/_app/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AppSessionsSessionIdRouteImport
      parentRoute: typeof AppSessionsRouteRoute
    }
    '/_app/instances/$instanceId': {
      id: '/_app/instances/$instanceId'
      path: '/$instanceId'
      fullPath: '/instances/$instanceId'
      preLoaderRoute: typeof AppInstancesInstanceIdRouteImport
      parentRoute: typeof AppInstancesRouteRoute
    }
    '/_app/cases/$caseId': {
      id: '/_app/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AppCasesCaseIdRouteImport
      parentRoute: typeof AppCasesRouteRoute
    }
  }
}

interface AppCasesRouteRouteChildren {
  AppCasesCaseIdRoute: typeof AppCasesCaseIdRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
}

const AppCasesRouteRouteChildren: AppCasesRouteRouteChildren = {
  AppCasesCaseIdRoute: AppCasesCaseIdRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
}

const AppCasesRouteRouteWithChildren = AppCasesRouteRoute._addFileChildren(
  AppCasesRouteRouteChildren,
)

interface AppInstancesRouteRouteChildren {
  AppInstancesInstanceIdRoute: typeof AppInstancesInstanceIdRoute
  AppInstancesIndexRoute: typeof AppInstancesIndexRoute
}

const AppInstancesRouteRouteChildren: AppInstancesRouteRouteChildren = {
  AppInstancesInstanceIdRoute: AppInstancesInstanceIdRoute,
  AppInstancesIndexRoute: AppInstancesIndexRoute,
}

const AppInstancesRouteRouteWithChildren =
  AppInstancesRouteRoute._addFileChildren(AppInstancesRouteRouteChildren)

interface AppSessionsRouteRouteChildren {
  AppSessionsSessionIdRoute: typeof AppSessionsSessionIdRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
}

const AppSessionsRouteRouteChildren: AppSessionsRouteRouteChildren = {
  AppSessionsSessionIdRoute: AppSessionsSessionIdRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
}

const AppSessionsRouteRouteWithChildren =
  AppSessionsRouteRoute._addFileChildren(AppSessionsRouteRouteChildren)

interface AppTasksRouteRouteChildren {
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppTasksRouteRouteChildren: AppTasksRouteRouteChildren = {
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppTasksRouteRouteWithChildren = AppTasksRouteRoute._addFileChildren(
  AppTasksRouteRouteChildren,
)

interface AppUsersRouteRouteChildren {
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppUsersRouteRouteChildren: AppUsersRouteRouteChildren = {
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppUsersRouteRouteWithChildren = AppUsersRouteRoute._addFileChildren(
  AppUsersRouteRouteChildren,
)

interface AppRouteChildren {
  AppCasesRouteRoute: typeof AppCasesRouteRouteWithChildren
  AppInstancesRouteRoute: typeof AppInstancesRouteRouteWithChildren
  AppSessionsRouteRoute: typeof AppSessionsRouteRouteWithChildren
  AppTasksRouteRoute: typeof AppTasksRouteRouteWithChildren
  AppUsersRouteRoute: typeof AppUsersRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppTgMenuIndexRoute: typeof AppTgMenuIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCasesRouteRoute: AppCasesRouteRouteWithChildren,
  AppInstancesRouteRoute: AppInstancesRouteRouteWithChildren,
  AppSessionsRouteRoute: AppSessionsRouteRouteWithChildren,
  AppTasksRouteRoute: AppTasksRouteRouteWithChildren,
  AppUsersRouteRoute: AppUsersRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppTgMenuIndexRoute: AppTgMenuIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
