import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    environment: 'node',
    env: {
      VITE_ADMIN_API_BASE: 'http://127.0.0.1:8081',
    },
    include: [
      'src/components/layout/hover-close.test.tsx',
      'src/scaffold.contract.test.ts',
      'src/auth-gates.contract.test.ts',
      'src/lib/setup-guard.test.ts',
      'src/features/setup/setup-steps.test.ts',
      'src/features/setup/db-dsn.test.ts',
      'src/features/setup/db-error.test.ts',
      'src/features/setup/blob-error.test.ts',
      'src/features/setup/setup-pages.contract.test.ts',
      'src/features/setup/setup-profile.contract.test.ts',
      'src/features/auth/register.contract.test.ts',
      'src/features/settings/settings-page.contract.test.ts',
      'src/lib/api/setup-settings.test.ts',
      'src/lib/api/client.test.ts',
      'src/vite-proxy.contract.test.ts',
      'src/dev-loop.contract.test.ts',
      'src/lib/api/edges.test.ts',
      'src/lib/api/cases.test.ts',
      'src/lib/api/channel-menu.test.ts',
      'src/lib/api/tasks.test.ts',
      'src/features/tasks/list-panel.contract.test.ts',
      'src/lib/api/task-errors.test.ts',
      'src/lib/api/localized-errors.test.ts',
      'src/lib/api/users.test.ts',
      'src/lib/api/admin-users.test.ts',
      'src/lib/api/sessions.test.ts',
      'src/features/sessions/list-panel.contract.test.ts',
      'src/lib/api/query-keys.test.ts',
      'src/lib/api/topics.test.ts',
      'src/lib/api/text-templates.test.ts',
      'src/lib/api/stats.test.ts',
      'src/lib/dashboard/aggregate.test.ts',
      'src/config/menu.test.ts',
      'src/lib/i18n/locale.test.ts',
      'src/lib/i18n/copy-quality.test.ts',
      'src/components/master-detail/master-detail.contract.test.ts',
      'src/components/kokonutui/mouse-effect-card.contract.test.ts',
      'src/components/layout/shell-layout.contract.test.ts',
      'src/components/ui/chart.contract.test.ts',
      'src/styles/theme-neutral.contract.test.ts',
      'src/features/cases/list-panel.contract.test.ts',
      'src/features/cases/workflow-editor.contract.test.ts',
      'src/features/cases/cases-detail.contract.test.ts',
      'src/features/cases/lib/node-catalog.test.ts',
      'src/features/cases/lib/workflow-parse.test.ts',
      'src/features/cases/lib/derive.test.ts',
      'src/lib/api/media.test.ts',
      'src/features/cases/sections/media-preview-field.contract.test.ts',
      'src/features/menu/lib/menu-flow.test.ts',
      'src/features/menu/menu-editor.contract.test.ts',
      'src/features/channels/channel-layout.contract.test.ts',
      'src/features/topics/topic-layout.contract.test.ts',
      'src/features/admin-users/admin-users-panel.contract.test.ts',
      'src/features/edges/edges.contract.test.ts',
      'src/features/edges/agent-credentials.test.ts',
      'src/features/edges/observation.test.ts',
      'src/features/edges/list-health.test.ts',
      'src/features/task-flow/lib/graph.test.ts',
      'src/features/task-flow/lib/elk-layout.test.ts',
      'src/features/task-flow/lib/topic-binding.test.ts',
      'src/features/task-flow/lib/validate.test.ts',
      'src/features/task-flow/task-flow.contract.test.ts',
      'src/features/quick-config/lib/readiness.test.ts',
      'src/features/quick-config/lib/session.test.ts',
      'src/features/quick-config/lib/menu-payload.test.ts',
      'src/features/quick-config/quick-config.contract.test.ts',
      'src/features/dashboard/date-range.test.ts',
      'src/features/dashboard/daily-to-activity.test.ts',
      'src/features/dashboard/workbench.contract.test.ts',
      'src/features/dashboard/task-stats-parse.test.ts',
      'src/features/dashboard/hardware-summary.test.ts',
      'src/features/config-context/config-chain.contract.test.ts',
      'src/features/link-health/link-health.contract.test.ts',
      'src/features/link-health/lib/references.test.ts',
    ],
  },
})
