import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    environment: 'node',
    env: {
      VITE_ADMIN_API_BASE: 'http://127.0.0.1:8081',
    },
    include: [
      'src/scaffold.contract.test.ts',
      'src/auth-gates.contract.test.ts',
      'src/lib/setup-guard.test.ts',
      'src/features/setup/setup-steps.test.ts',
      'src/features/setup/setup-pages.contract.test.ts',
      'src/features/settings/settings-page.contract.test.ts',
      'src/lib/api/setup-settings.test.ts',
      'src/lib/api/client.test.ts',
      'src/vite-proxy.contract.test.ts',
      'src/dev-loop.contract.test.ts',
      'src/lib/api/edges.test.ts',
      'src/lib/api/cases.test.ts',
      'src/lib/api/channel-menu.test.ts',
      'src/lib/api/tasks.test.ts',
      'src/lib/api/task-errors.test.ts',
      'src/lib/api/users.test.ts',
      'src/lib/api/sessions.test.ts',
      'src/lib/api/query-keys.test.ts',
      'src/lib/dashboard/aggregate.test.ts',
      'src/config/menu.test.ts',
      'src/lib/i18n/locale.test.ts',
      'src/components/master-detail/master-detail.contract.test.ts',
      'src/components/layout/shell-layout.contract.test.ts',
      'src/styles/theme-neutral.contract.test.ts',
      'src/features/cases/menu-placements.contract.test.ts',
      'src/features/cases/workflow-editor.contract.test.ts',
      'src/features/cases/cases-detail.contract.test.ts',
      'src/features/cases/lib/node-catalog.test.ts',
      'src/features/cases/lib/workflow-parse.test.ts',
      'src/features/cases/lib/derive.test.ts',
      'src/features/menu/lib/menu-flow.test.ts',
      'src/features/menu/menu-editor.contract.test.ts',
      'src/features/channels/channel-layout.contract.test.ts',
      'src/features/edges/edges.contract.test.ts',
      'src/features/edges/agent-credentials.test.ts',
      'src/features/edges/observation.test.ts',
      'src/features/edges/list-health.test.ts',
      'src/features/task-flow/lib/graph.test.ts',
      'src/features/task-flow/lib/elk-layout.test.ts',
      'src/features/task-flow/lib/topic-binding.test.ts',
      'src/features/task-flow/lib/validate.test.ts',
      'src/features/task-flow/task-flow.contract.test.ts',
    ],
  },
})
