import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const here = dirname(fileURLToPath(import.meta.url))

function read(rel: string) {
  return readFileSync(join(here, rel), 'utf8')
}

describe('compute node layout and detail', () => {
  it('puts create on the page title row and searches by name only', () => {
    const layout = read('../../routes/_app/edges/route.tsx')
    const list = read('list-panel.tsx')
    expect(layout).toMatch(/lg:flex-row lg:items-center lg:justify-between/)
    expect(layout).toMatch(/flex min-w-0 flex-col gap-\[6px\]/)
    expect(layout).toMatch(/leading-tight font-semibold tracking-tight/)
    expect(layout).not.toMatch(/font-bold/)
    expect(layout).toMatch(/md:grid-cols-\[280px_1fr\]/)
    expect(list).not.toMatch(/border-b px-4 py-3/)
    expect(list).toMatch(/<Input/)
    expect(list).not.toMatch(/item\.base_url/)
  })

  it('copies subscription-detail classes without tabs', () => {
    const detail = read('detail-panel.tsx')
    const form = read('edge-form.tsx')
    const observe = read('observation-panel.tsx')
    const tags = read('presence-tags.tsx')
    const kit = read('kit-classes.ts')
    expect(detail).toMatch(/kit\.pageSection/)
    expect(detail).toMatch(/flex min-w-0 flex-col gap-\[6px\]/)
    expect(detail).toMatch(/data-orientation=['"]horizontal['"]/)
    expect(detail).toMatch(/grid-cols-\[7rem_minmax\(0,1fr\)\]/)
    expect(kit).toMatch(/grid-cols-\[7rem_minmax\(0,1fr\)\]/)
    expect(detail).not.toMatch(/tabInfo/)
    expect(detail).not.toMatch(/TabsTrigger/)
    expect(observe).not.toMatch(/md:grid-cols-3/)
    expect(detail).toMatch(/PenLine/)
    expect(detail).toMatch(/Terminal/)
    expect(form).toMatch(/RefreshCcw/)
    expect(tags).not.toMatch(/from '@\/components\/ui\/badge'/)
  })

  it('opens create edit and deploy in dialogs', () => {
    const detail = read('detail-panel.tsx')
    const form = read('edge-form.tsx')
    const layout = read('../../routes/_app/edges/route.tsx')
    expect(detail).toMatch(/<Dialog/)
    expect(form).toMatch(/refresh_hardware/)
    expect(form).not.toMatch(/htmlFor=['"]edge-host['"]/)
    expect(form).not.toMatch(/htmlFor=['"]edge-port['"]/)
    expect(form).not.toMatch(/htmlFor=['"]instance-id['"]/)
    expect(layout).not.toMatch(/edgeId === 'new'/)
    expect(layout).toMatch(/<Dialog/)
  })

  it('defaults to the first node and offers create from empty detail', () => {
    const layout = read('../../routes/_app/edges/route.tsx')
    const shell = read('../../components/master-detail/master-detail-shell.tsx')
    const zh = read('../../lib/i18n/locales/zh.json')
    expect(layout).toMatch(
      /edgeId \?\? \(backToList \? undefined : items\[0\]\?\.id\)/
    )
    expect(layout).toMatch(/emptyDetail=/)
    expect(layout).toMatch(/EmptyHeader/)
    expect(layout).toMatch(/setCreateOpen\(true\)/)
    expect(layout).toContain("to: '/edges/$edgeId'")
    expect(layout).toContain('replace: true')
    expect(shell).toMatch(/emptyDetail \?\? /)
    expect(zh).toMatch(/"createNode": "新建节点"/)
  })

  it('shows a health dot in the list and polls presence every 5s', () => {
    const list = read('list-panel.tsx')
    const layout = read('../../routes/_app/edges/route.tsx')
    const observe = read('observation-panel.tsx')
    const zh = read('../../lib/i18n/locales/zh.json')
    expect(list).toMatch(/listHealthTone/)
    expect(list).toMatch(/data-health/)
    expect(list).not.toMatch(/PresenceTags/)
    expect(list).not.toMatch(/edges\.enabled/)
    expect(layout).toMatch(/listPresence/)
    expect(layout).toMatch(/refetchInterval:\s*5000/)
    const listQuery = layout.match(
      /useQuery\(\{[\s\S]*?queryFn:\s*listEdges[\s\S]*?\}\)/
    )?.[0]
    expect(listQuery).toBeTruthy()
    expect(listQuery).not.toMatch(/refetchInterval/)
    expect(observe).not.toMatch(/PresenceTags/)
    expect(observe).not.toMatch(/edges\.reachable/)
    expect(zh).toMatch(/"nodeOnline": "节点在线"/)
    expect(zh).toMatch(/"nodeOffline": "节点掉线"/)
    expect(zh).toMatch(/"comfyRunning": "Comfy运行中"/)
    expect(zh).toMatch(/"comfyStopped": "Comfy未启动"/)
  })

  it('keeps deploy command on EDGE_ID', () => {
    const creds = read('agent-credentials.tsx')
    const deploy = read('deploy-command.ts')
    expect(creds).toMatch(/agent_token/)
    expect(deploy).toMatch(/CONTROL_PLANE_URL/)
    expect(deploy).toMatch(/EDGE_ID/)
    expect(deploy).not.toMatch(/INSTANCE_ID/)
    expect(deploy).toMatch(/AGENT_TOKEN/)
    expect(deploy).toMatch(/COMFYUI_BASE_URL=\$\{comfyURL\}/)
    expect(deploy).toMatch(/127\.0\.0\.1:8188/)
    expect(creds).toMatch(/rotateEdgeToken/)
    expect(creds).toMatch(/PasswordInput/)
    expect(creds).toMatch(/maskToken:\s*true/)
    expect(creds).toMatch(/<pre/)
    expect(creds).not.toMatch(/showCommand/)
  })

  it('locks system monitoring chart classes and copy', () => {
    const chart = read('../../components/ui/chart.tsx')
    const observe = read('observation-panel.tsx')
    const detail = read('detail-panel.tsx')
    const zh = read('../../lib/i18n/locales/zh.json')
    const en = read('../../lib/i18n/locales/en.json')
    expect(chart).toMatch(/data-slot="chart"/)
    expect(chart).toMatch(/aspect-video/)
    expect(observe).toMatch(/aspect-auto/)
    expect(observe).toMatch(/h-full min-h-\[120px\] w-full min-w-0/)
    expect(observe).toMatch(
      /orientation='right'\s+tickFormatter=\{\(v: number\) => formatBytes\(v\)\}\s+width=\{70\}/
    )
    expect(observe).not.toMatch(/formatBytes\(v\)\}\s*width=\{(48|64|80)\}/)
    expect(observe).toMatch(/text-base font-semibold/)
    expect(observe).toMatch(/lg:grid-cols-\[minmax\(0,1fr\)_62px\]/)
    expect(observe).toMatch(/lg:grid-cols-\[minmax\(0,1fr\)_122px\]/)
    expect(observe).not.toMatch(/lg:grid-cols-\[minmax\(0,1fr\)_92px\]/)
    expect(observe).toMatch(/grid min-h-0 flex-1 gap-1\.5/)
    expect(observe).not.toMatch(/grid min-h-0 flex-1 gap-2/)
    expect(observe).toMatch(/inline-flex items-center gap-1\.5/)
    expect(observe).not.toMatch(/legend\.length > 1/)
    expect(observe).toMatch(/ioStats\(/)
    expect(observe).toMatch(/monitorIoReadCurrent/)
    expect(observe).toMatch(/monitorIoWriteAvg/)
    expect(observe).toMatch(/\bcompact\b/)
    expect(observe).toMatch(/text-xs leading-5 font-semibold/)
    expect(observe).toMatch(
      /text-\[11px\] text-muted-foreground|text-muted-foreground text-\[11px\]/
    )
    expect(observe).toMatch(/seriesStats\(/)
    expect(observe).toMatch(/edges\.monitorCurrent/)
    expect(observe).toMatch(/edges\.monitorMax/)
    expect(observe).toMatch(/edges\.monitorAvg/)
    expect(observe).toMatch(/text-lg leading-6 font-semibold/)
    expect(observe).not.toMatch(/text-xl leading-6 font-semibold/)
    expect(observe).not.toMatch(/size-\[100px\] shrink-0 sm:size-\[120px\]/)
    expect(observe).not.toMatch(/PieChart/)
    expect(observe).toMatch(/LineChart/)
    expect(observe).toMatch(/usageConfig\[`gpu\$\{gi\}`\]/)
    expect(observe).toMatch(/vramConfig\[`gpu\$\{gi\}Rate`\]/)
    expect(observe).toMatch(/multi \? `GPU\$\{gi\}`/)
    expect(observe).toMatch(/dataKey=\{`gpu\$\{gi\}`\}/)
    expect(observe).toMatch(/dataKey=\{`gpu\$\{gi\}Rate`\}/)
    expect(observe).not.toMatch(
      /\$\{t\('edges\.monitorGpuUsage'\)\} · \$\{name\}/
    )
    expect(observe).toMatch(
      /color-mix\(in oklch, var\(--primary\) 75%, var\(--background\)\)/
    )
    expect(observe).toMatch(/var\(--primary\)/)
    expect(observe).not.toMatch(/getEdgeSystem/)
    expect(detail).not.toMatch(/getEdgeSystem/)
    expect(zh).toMatch(/"observationSystem": "系统监控"/)
    expect(zh).toMatch(/"observationSystemHint": "节点实时监控"/)
    expect(en).toMatch(/"observationSystem": "System Monitoring"/)
    expect(zh).toMatch(/"monitorMemRate": "内存占用率"/)
    expect(en).toMatch(/"monitorMemRate": "Memory usage"/)
    expect(zh).toMatch(/"monitorVramRate": "显存占用率"/)
    expect(en).toMatch(/"monitorVramRate": "VRAM usage"/)
    expect(zh).toMatch(/"monitorIoReadCurrent": "当前读"/)
    expect(zh).toMatch(/"monitorIoReadMax": "最高读"/)
    expect(zh).toMatch(/"monitorIoReadAvg": "平均读"/)
    expect(zh).toMatch(/"monitorIoWriteCurrent": "当前写"/)
    expect(zh).toMatch(/"monitorIoWriteMax": "最高写"/)
    expect(zh).toMatch(/"monitorIoWriteAvg": "平均写"/)
    expect(en).toMatch(/"monitorIoReadCurrent": "Current read"/)
    expect(en).toMatch(/"monitorIoReadMax": "Highest read"/)
    expect(en).toMatch(/"monitorIoReadAvg": "Average read"/)
    expect(en).toMatch(/"monitorIoWriteCurrent": "Current write"/)
    expect(en).toMatch(/"monitorIoWriteMax": "Highest write"/)
    expect(en).toMatch(/"monitorIoWriteAvg": "Average write"/)
    expect(zh).toMatch(/"monitorEmptyHint": "请检查节点状态/)
    expect(en).toMatch(/"monitorEmptyHint": "Check the node/)
    expect(zh).toMatch(/"monitorCurrent": "当前"/)
    expect(en).toMatch(/"monitorCurrent": "Current"/)
    expect(zh).toMatch(/"monitorMax": "最高"/)
    expect(en).toMatch(/"monitorMax": "Highest"/)
    expect(zh).toMatch(/"monitorAvg": "平均"/)
    expect(en).toMatch(/"monitorAvg": "Average"/)
    expect(detail).toMatch(/getEdgeMetrics/)
    expect(detail).toMatch(/refetchInterval:\s*15000/)
  })
})
